package com.tgspeechbox.tts

import android.os.Bundle
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Test
import java.io.File
import java.util.Locale
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * Issue #100 / #95 /s/-/z/ Android probe.
 *
 * Renders a controlled set of Spanish words via the production TGSpeechBox
 * TTS engine using TextToSpeech.synthesizeToFile, bypassing the audio
 * playback layer entirely. Output WAVs land in the app's external files
 * directory, pullable via adb. Comparing these against the SAPI/Linux
 * rendering of the same words isolates whether the bug is in the engine
 * (output WAV is wrong) or in the audio playback path (WAV is right).
 *
 * Test words cover:
 *   - The reported failures: Restablecer, Seleccionado, Espanol
 *   - Voiced /s/ controls in expected-voicing positions: rosa, mismo
 *   - /s/ in cluster contexts: suspendido, escuchar, espuela
 *   - Recently-fixed Spanish /g/ words to confirm no regression: dialogo, lago
 */
class ProbeTest {
    @Test
    fun synthesizeProbeWords() {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val outDir = File(ctx.getExternalFilesDir(null), "android_probe")
        outDir.mkdirs()
        // Drop a marker so the puller knows where to look
        File(outDir, "DIR_README.txt").writeText(
            "Generated by ProbeTest. Pull via:\n" +
            "  adb pull /sdcard/Android/data/com.tgspeechbox.tts/files/android_probe/\n"
        )

        val initLatch = CountDownLatch(1)
        var initStatus = -1
        val tts = TextToSpeech(
            ctx,
            TextToSpeech.OnInitListener { status ->
                initStatus = status
                initLatch.countDown()
            },
            "com.tgspeechbox.tts"
        )

        check(initLatch.await(20, TimeUnit.SECONDS)) { "TTS init timeout" }
        check(initStatus == TextToSpeech.SUCCESS) {
            "TTS init failed with status $initStatus"
        }

        val locale = Locale("es", "MX")
        val langStatus = tts.setLanguage(locale)
        File(outDir, "INIT_LOG.txt").writeText(
            "init_status=$initStatus\n" +
            "lang_status=$langStatus\n" +
            "engine=${tts.defaultEngine}\n" +
            "available_voices=${tts.voices?.joinToString(", ") { it.name } ?: "<null>"}\n"
        )

        // (word, file_basename) — basename is ASCII-safe for adb pull
        val words = listOf(
            "Restablecer" to "restablecer",
            "Seleccionado" to "seleccionado",
            "Español" to "espanol",
            "casa" to "casa_ctrl",
            "rosa" to "rosa_voicedctx",
            "mismo" to "mismo_voicedctx",
            "suspendido" to "suspendido",
            "escuchar" to "escuchar",
            "espuela" to "espuela",
            "diálogo" to "dialogo_check",
            "lago" to "lago_check",
            "amigo" to "amigo_check"
        )

        for ((word, basename) in words) {
            val out = File(outDir, "$basename.wav")
            val latch = CountDownLatch(1)
            tts.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                override fun onStart(utteranceId: String?) {}
                override fun onDone(utteranceId: String?) { latch.countDown() }
                @Deprecated("legacy")
                override fun onError(utteranceId: String?) { latch.countDown() }
                override fun onError(utteranceId: String?, errorCode: Int) { latch.countDown() }
            })
            val params = Bundle()
            val res = tts.synthesizeToFile(word, params, out, basename)
            // res != SUCCESS means engine refused — log it but keep going
            if (res != TextToSpeech.SUCCESS) {
                File(outDir, "$basename.err").writeText("synthesizeToFile returned $res\n")
                continue
            }
            check(latch.await(25, TimeUnit.SECONDS)) {
                "Synth timeout for $word"
            }
        }

        tts.shutdown()
    }

    /**
     * Rate-sweep variant. Renders the same /s/-bearing words at three
     * speech rates (1.0x, 1.5x, 2.0x) into rate-tagged subdirs.
     * Hypothesis under test (issue #100, 29-Bloo 2026-05-06):
     * "in this Android context, when synthesis is used with screen readers,
     *  at low speeds it does not seem to occur, while at normal speed the
     *  Z sound is constant."
     *
     * If the engine produces clean /s/ at all three rates here, the bug is
     * confirmed to be in the playback path (TalkBack-mediated audio session
     * + Samsung audio enhancements interacting with rate-dependent buffer
     * timing). If the higher-rate WAVs show voicing leak, the bug is in the
     * engine after all and rate-dependent.
     */
    @Test
    fun synthesizeAtMultipleRates() {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val baseDir = File(ctx.getExternalFilesDir(null), "android_probe_rates")
        baseDir.mkdirs()
        File(baseDir, "DIR_README.txt").writeText(
            "Generated by ProbeTest.synthesizeAtMultipleRates. Pull via:\n" +
            "  adb pull /sdcard/Android/data/com.tgspeechbox.tts/files/android_probe_rates/\n"
        )

        val initLatch = CountDownLatch(1)
        var initStatus = -1
        val tts = TextToSpeech(
            ctx,
            TextToSpeech.OnInitListener { status ->
                initStatus = status
                initLatch.countDown()
            },
            "com.tgspeechbox.tts"
        )
        check(initLatch.await(20, TimeUnit.SECONDS)) { "TTS init timeout" }
        check(initStatus == TextToSpeech.SUCCESS) {
            "TTS init failed: $initStatus"
        }
        tts.setLanguage(Locale("es", "MX"))

        // Word -> safe-filename basename
        val words = listOf(
            "Restablecer" to "restablecer",
            "Seleccionado" to "seleccionado",
            "Español" to "espanol",
            "suspendido" to "suspendido"
        )
        // Rates to test: 1.0 = nominal, 1.5 ≈ TalkBack default, 2.0 = fast
        val rates = listOf(1.0f, 1.5f, 2.0f)

        for (rate in rates) {
            val rateLabel = String.format(Locale.US, "%.1f", rate)
            val rateDir = File(baseDir, "rate_${rateLabel}x")
            rateDir.mkdirs()
            tts.setSpeechRate(rate)
            File(rateDir, "INIT_LOG.txt").writeText(
                "speech_rate=${rate}\n"
            )

            for ((word, basename) in words) {
                val out = File(rateDir, "$basename.wav")
                val latch = CountDownLatch(1)
                tts.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                    override fun onStart(utteranceId: String?) {}
                    override fun onDone(utteranceId: String?) { latch.countDown() }
                    @Deprecated("legacy")
                    override fun onError(utteranceId: String?) { latch.countDown() }
                    override fun onError(utteranceId: String?, errorCode: Int) {
                        latch.countDown()
                    }
                })
                val params = Bundle()
                val res = tts.synthesizeToFile(word, params, out, "${basename}_${rate}")
                if (res != TextToSpeech.SUCCESS) {
                    File(rateDir, "$basename.err").writeText(
                        "synthesizeToFile returned $res at rate $rate\n"
                    )
                    continue
                }
                check(latch.await(25, TimeUnit.SECONDS)) {
                    "Synth timeout for $word at rate $rate"
                }
            }
        }

        tts.shutdown()
    }

    /**
     * Live-playback variant. Uses tts.speak() instead of synthesizeToFile,
     * so the audio actually goes through the AudioTrack/playback path.
     * Bug-reported words played twice with brief pause for ear-test.
     */
    @Test
    fun playWordsLive() {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val initLatch = CountDownLatch(1)
        var initStatus = -1
        val tts = TextToSpeech(
            ctx,
            TextToSpeech.OnInitListener { status ->
                initStatus = status
                initLatch.countDown()
            },
            "com.tgspeechbox.tts"
        )
        check(initLatch.await(20, TimeUnit.SECONDS)) { "TTS init timeout" }
        check(initStatus == TextToSpeech.SUCCESS) {
            "TTS init failed: $initStatus"
        }
        tts.setLanguage(Locale("es", "MX"))
        tts.setSpeechRate(1.0f)

        fun say(text: String, id: String, waitMs: Long) {
            val latch = CountDownLatch(1)
            tts.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                override fun onStart(utteranceId: String?) {}
                override fun onDone(utteranceId: String?) { latch.countDown() }
                @Deprecated("legacy")
                override fun onError(utteranceId: String?) { latch.countDown() }
                override fun onError(utteranceId: String?, errorCode: Int) { latch.countDown() }
            })
            tts.speak(text, TextToSpeech.QUEUE_FLUSH, null, id)
            check(latch.await(20, TimeUnit.SECONDS)) { "Speak timeout for $text" }
            Thread.sleep(waitMs)
        }

        // #100 words: /s/,/c/,/z/ that the device DSP was ducking toward /z/.
        // Speak each TWICE (the device duck often only hits the first hearing),
        // with an English orienting cue first so Tomi can get his ears ready.
        val words = listOf("restablecer", "seleccionado", "español", "suspendido")

        say("Testing", "intro", 1200)
        for ((i, word) in words.withIndex()) {
            say(word, "live_${i}a", 700)
            say(word, "live_${i}b", 1100)
        }

        tts.shutdown()
    }

    /**
     * State forensics for the Español/escuchar dark-/s/ investigation.
     * Desktop ruled out every static input (packs, espeak data+version+voice,
     * text, WithText-vs-direct) — remaining suspect is on-device override
     * state applied via applyStoredOverrides: phoneme_overrides,
     * pack_overrides_<lang>, dict_overrides_<lang>, dict_disabled_<lang>
     * in tgsb_settings SharedPreferences. Dump all prefs verbatim plus a
     * recursive filesDir listing for adb pull.
     */
    @Test
    fun dumpEngineState() {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val outDir = File(ctx.getExternalFilesDir(null), "state_dump")
        outDir.mkdirs()

        val prefs = ctx.getSharedPreferences("tgsb_settings", 0)
        val sb = StringBuilder()
        for ((k, v) in prefs.all.toSortedMap()) {
            sb.append(k).append(" = ").append(v).append('\n')
        }
        File(outDir, "prefs.txt").writeText(sb.toString())

        val fl = StringBuilder()
        fun walk(dir: File, indent: String) {
            val entries = dir.listFiles() ?: return
            for (e in entries.sortedBy { it.name }) {
                fl.append(indent).append(e.name)
                if (e.isDirectory) {
                    fl.append("/\n")
                    walk(e, "$indent  ")
                } else {
                    fl.append("  ").append(e.length()).append('\n')
                }
            }
        }
        walk(ctx.filesDir, "")
        File(outDir, "filesdir.txt").writeText(fl.toString())
    }

    /**
     * On-device A/B: same IPA through queueIPA_Ex (direct, the path the
     * desktop harness uses) vs queueIPA_ExWithText (the production path),
     * running on the REAL ARM binary with the device's espeak + packs.
     * Also logs the device espeak's IPA per word — the last unverified
     * input. Desktop showed the two paths byte-identical on x64; if they
     * differ here, the fork is ARM/JNI-side; if direct is dark too, the
     * fork is in the ARM token pipeline itself.
     */
    @Test
    fun directVsWithText() {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val outDir = File(ctx.getExternalFilesDir(null), "direct_vs_withtext")
        outDir.mkdirs()

        val sr = 22050
        val handle = DebugNatives.nativeCreate(
            ctx.filesDir.absolutePath,
            File(ctx.filesDir, "tgsb").absolutePath,
            sr
        )
        check(handle != 0L) { "nativeCreate failed" }
        check(DebugNatives.nativeSetLanguage(handle, "es-mx", "es-mx") == 0) {
            "setLanguage failed"
        }

        val words = listOf(
            "Español" to "espanol",
            "escuchar" to "escuchar",
            "espuela" to "espuela",
            "casa" to "casa",
            "suspendido" to "suspendido"
        )

        fun pullAllPcm(): ByteArray {
            val buf = ByteArray(8192)
            val out = java.io.ByteArrayOutputStream()
            while (true) {
                val n = DebugNatives.nativePullAudio(handle, buf, buf.size)
                if (n <= 0) break
                out.write(buf, 0, n)
            }
            return out.toByteArray()
        }

        fun writeWav(f: File, pcm: ByteArray) {
            val dataLen = pcm.size
            val hdr = java.nio.ByteBuffer.allocate(44)
                .order(java.nio.ByteOrder.LITTLE_ENDIAN)
            hdr.put("RIFF".toByteArray()).putInt(36 + dataLen)
            hdr.put("WAVE".toByteArray()).put("fmt ".toByteArray())
            hdr.putInt(16).putShort(1).putShort(1).putInt(sr)
            hdr.putInt(sr * 2).putShort(2).putShort(16)
            hdr.put("data".toByteArray()).putInt(dataLen)
            f.outputStream().use { s ->
                s.write(hdr.array())
                s.write(pcm)
            }
        }

        val log = StringBuilder()
        for ((word, base) in words) {
            val ipa = DebugNatives.nativeTextToIpa(handle, word)
            log.append("$word -> [$ipa]\n")

            val fd = DebugNatives.nativeDebugQueueIpaEx(
                handle, null, ipa, 1.0, 140.0, false)
            writeWav(File(outDir, "${base}_direct.wav"), pullAllPcm())

            val fw = DebugNatives.nativeDebugQueueIpaEx(
                handle, word, ipa, 1.0, 140.0, true)
            writeWav(File(outDir, "${base}_withtext.wav"), pullAllPcm())

            log.append("  frames direct=$fd withtext=$fw\n")
        }
        File(outDir, "ipa_log.txt").writeText(log.toString())
        DebugNatives.nativeDestroy(handle)
    }
}
