package com.tgspeechbox.tts

import android.os.Bundle
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Test
import java.io.File
import java.util.Locale
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * Issue #100 / #95 /s/-/z/ Android probe.
 *
 * Renders a controlled set of Spanish words via the production TGSpeechBox
 * TTS engine using TextToSpeech.synthesizeToFile, bypassing the audio
 * playback layer entirely. Output WAVs land in the app's external files
 * directory, pullable via adb. Comparing these against the SAPI/Linux
 * rendering of the same words isolates whether the bug is in the engine
 * (output WAV is wrong) or in the audio playback path (WAV is right).
 *
 * Test words cover:
 *   - The reported failures: Restablecer, Seleccionado, Espanol
 *   - Voiced /s/ controls in expected-voicing positions: rosa, mismo
 *   - /s/ in cluster contexts: suspendido, escuchar, espuela
 *   - Recently-fixed Spanish /g/ words to confirm no regression: dialogo, lago
 */
class ProbeTest {
    @Test
    fun synthesizeProbeWords() {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val outDir = File(ctx.getExternalFilesDir(null), "android_probe")
        outDir.mkdirs()
        // Drop a marker so the puller knows where to look
        File(outDir, "DIR_README.txt").writeText(
            "Generated by ProbeTest. Pull via:\n" +
            "  adb pull /sdcard/Android/data/com.tgspeechbox.tts/files/android_probe/\n"
        )

        val initLatch = CountDownLatch(1)
        var initStatus = -1
        val tts = TextToSpeech(
            ctx,
            TextToSpeech.OnInitListener { status ->
                initStatus = status
                initLatch.countDown()
            },
            "com.tgspeechbox.tts"
        )

        check(initLatch.await(20, TimeUnit.SECONDS)) { "TTS init timeout" }
        check(initStatus == TextToSpeech.SUCCESS) {
            "TTS init failed with status $initStatus"
        }

        val locale = Locale("es", "MX")
        val langStatus = tts.setLanguage(locale)
        File(outDir, "INIT_LOG.txt").writeText(
            "init_status=$initStatus\n" +
            "lang_status=$langStatus\n" +
            "engine=${tts.defaultEngine}\n" +
            "available_voices=${tts.voices?.joinToString(", ") { it.name } ?: "<null>"}\n"
        )

        // (word, file_basename) — basename is ASCII-safe for adb pull
        val words = listOf(
            "Restablecer" to "restablecer",
            "Seleccionado" to "seleccionado",
            "Español" to "espanol",
            "casa" to "casa_ctrl",
            "rosa" to "rosa_voicedctx",
            "mismo" to "mismo_voicedctx",
            "suspendido" to "suspendido",
            "escuchar" to "escuchar",
            "espuela" to "espuela",
            "diálogo" to "dialogo_check",
            "lago" to "lago_check",
            "amigo" to "amigo_check"
        )

        for ((word, basename) in words) {
            val out = File(outDir, "$basename.wav")
            val latch = CountDownLatch(1)
            tts.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                override fun onStart(utteranceId: String?) {}
                override fun onDone(utteranceId: String?) { latch.countDown() }
                @Deprecated("legacy")
                override fun onError(utteranceId: String?) { latch.countDown() }
                override fun onError(utteranceId: String?, errorCode: Int) { latch.countDown() }
            })
            val params = Bundle()
            val res = tts.synthesizeToFile(word, params, out, basename)
            // res != SUCCESS means engine refused — log it but keep going
            if (res != TextToSpeech.SUCCESS) {
                File(outDir, "$basename.err").writeText("synthesizeToFile returned $res\n")
                continue
            }
            check(latch.await(25, TimeUnit.SECONDS)) {
                "Synth timeout for $word"
            }
        }

        tts.shutdown()
    }

    /**
     * Live-playback variant. Uses tts.speak() instead of synthesizeToFile,
     * so the audio actually goes through the AudioTrack/playback path.
     * Bug-reported words played twice with brief pause for ear-test.
     */
    @Test
    fun playWordsLive() {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val initLatch = CountDownLatch(1)
        var initStatus = -1
        val tts = TextToSpeech(
            ctx,
            TextToSpeech.OnInitListener { status ->
                initStatus = status
                initLatch.countDown()
            },
            "com.tgspeechbox.tts"
        )
        check(initLatch.await(20, TimeUnit.SECONDS)) { "TTS init timeout" }
        check(initStatus == TextToSpeech.SUCCESS) {
            "TTS init failed: $initStatus"
        }
        tts.setLanguage(Locale("es", "MX"))

        // Words tester reported as /s/ -> /z/. Play each with a marker
        // string between so logcat / Tomi can isolate which utterance
        // is which.
        val words = listOf("restablecer", "Seleccionado", "Espanol", "suspendido")

        for ((i, word) in words.withIndex()) {
            val latch = CountDownLatch(1)
            tts.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                override fun onStart(utteranceId: String?) {}
                override fun onDone(utteranceId: String?) { latch.countDown() }
                @Deprecated("legacy")
                override fun onError(utteranceId: String?) { latch.countDown() }
                override fun onError(utteranceId: String?, errorCode: Int) { latch.countDown() }
            })
            tts.speak(word, TextToSpeech.QUEUE_FLUSH, null, "live_$i")
            check(latch.await(20, TimeUnit.SECONDS)) { "Speak timeout for $word" }
            // Brief pause between words for ear-test isolation
            Thread.sleep(800)
        }

        tts.shutdown()
    }
}
